entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: true
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

app:
  dashboard: true

log:
  level: INFO
